sudo: required

services:
  - docker

language: go
go:
  - 1.8.3

env:
  global:
    - IMAGE_TAG=$DOCKER_USERNAME/show-headers

install:
  - # an empty install saves the hassle of pseudo-getting deps (they're vendored, so no need!)

script:
  - go build -a -tags netgo -ldflags '-s -w' -o show-headers
  - docker build --pull=true --rm=true -t "$IMAGE_TAG" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE_TAG;
    fi
